In [126]:
# Reverse a string:
 # Write a function that takes a string as input and returns the string in reverse order.

def reverse_string(string):
    return string[::-1]
reverse_string("Hello")

def reverse_string(string):
    return string[::-1]
reverse_string("Hello")

'olleH'

In [128]:
# # Find the factorial of a number:
# # Write a function that takes an integer as input and returns its factorial.
def factorial(num):
    if num==1:
        return num
    else:
        return num*factorial(num-1)
factorial(5)


120

In [1]:
# # Check if a string is a palindrome:
# # Write a function that takes a string as input and returns True if it is a palindrome, and False otherwise.
def palyndrome(string):
    if string == string[::-1]:
        return "Palyndrome"
    else:
        return 'False'
palyndrome("madam")

'Palyndrome'

In [2]:
# # Find the common elements in two lists:
# # Write a function that takes two lists as input and returns a list of common elements between the two.
li = [1,2,3,4,5]
li1 = [4,5,6,7]

cl = [i for i in li if i in li1]
print(cl)

def common_elements(li,li1):
    empty = []
    for i in li:
        if i in li1:
            empty.append(i)
    return empty
print(common_elements(li,li1))

[4, 5]
[4, 5]


In [4]:
# # Count the frequency of each element in a list:
# # Write a function that takes a list as input and returns a dictionary with the frequency of each element.

# # Example:
# # Input: [1, 2, 2, 3, 3, 3]
# # Output: {1: 1, 2: 2, 3: 3}
dic = [1,2,2,3,3,3]
cm = {i:dic.count(i) for i in  dic }

print(cm)



def frequency(dic):
    empty={}
    for i in dic:
        if i in empty:
            empty[i]+=1
        else:
            empty[i]=1
    return empty
print(frequency(dic))


def frequency(dic):
    empty = {}
    for i in dic:
        empty[i]=dic.count(i)
    return empty
print(frequency(dic))

cmp = {i:dic.count(i) for i in dic }
print(cmp)


{1: 1, 2: 2, 3: 3}
{1: 1, 2: 2, 3: 3}
{1: 1, 2: 2, 3: 3}
{1: 1, 2: 2, 3: 3}


In [ ]:
# # Implement a stack using a list:
# # Write a class that implements a stack data structure using a list (or array) in Python.
# # It should have push(), pop(), and is_empty() methods.

class Stack:
    def __init__(self):
        self.stack =[]
    def push(self,item):
        self.stack.append(item)
    def pop(self):
        if self.is_empty():
            raise IndexError('Stack is Empty')
        return self.stack.pop()
    def is_empty(self):
        return len(self.stack)==0
stack = Stack()
stack.push(1)
stack.push(2)
stack.push(3)

print(stack.pop())
print(stack.pop())
print(stack.is_empty())
print(stack.pop())
print(stack.is_empty())

In [142]:
# # Check if two strings are anagrams:
# # Write a function that takes two strings as input and returns True if they are anagrams (contain the same characters in any order), and False otherwise.

# # Example:
# # Input: "listen", "silent"
# # Output: True

str1 = "listen"
str2 = "silent"
def Anagram(str1,str2):
    if sorted(str1)==sorted(str2):
        return 'Anagram'
    else:
        return 'Not Anagram'
Anagram(str1,str2)
    



'Anagram'

In [145]:
# # Python program to display all the prime numbers within an interval

lower = 900
upper = 1000

for num in range(lower,upper+1):
    if num>1:
        for i in range(2,num):
            if num%i==0:
                break
        else:
            print(num)
    
# # Python program to check whther the number is prime or not.

num = 29

for i in range(2,num):
    if num%i==0:
        print('Not prime')
        break
else:
    print('prime')



907
911
919
929
937
941
947
953
967
971
977
983
991
997
prime


In [146]:
# # Reverse a string

string = "Ojas Innovative Technlogies"

def empty_string(string):
    s = ''
    for i in string:
        s=i+s
    return s
empty_string(string)


'seiglnhceT evitavonnI sajO'

In [ ]:
# # sort the array without builtin methods

array = [1,-1,90,3,2,0,45,25,12,78,37]

for i in range(len(array)):
    for j in range(len(array)):
        if array[i]<array[j]:
            array[i],array[j]=array[j],array[i]

print(array)

In [150]:
 #Write a Python program to get a new string from a given string where "Is" has been added to the front. If the given string already begins with "Is" then return the string unchanged.
string ="Bhargav"

if len(string)>2 and string[:2]=="Is":
    print(string)
else:
    print("is"+string)

isBhargav


In [152]:
# Write a Python program to calculate the sum of three given numbers, if the values are equal then return thrice of their sum.
def sum(a,b,c):
    sum = a+b+c
    if a==b==c:
        sum = sum*3
    return sum
sum(1,2,3)
sum(3,3,3)


27

In [156]:
# #  Write a Python program to test whether a number is within 100 of 1000 or 2000

num = 101
for i in range(100,2000):
    if i == num:
        print(True)
        break
else:
    print(False)

True


In [157]:
# # Write a Python program to calculate number of days between two dates.
from datetime import date

x = date(2014,9,9)
y = date(2020,9,9)
print(x-y)

-2192 days, 0:00:00


In [160]:
# # Write a Python program to print the calendar of a given month and year.
import calendar
month = 2
year = 2023
print(calendar.month(year,month))

   February 2023
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28



In [165]:
# # Write a Python program to accept a filename from the user and print the extension of that.
file_name = input('Enter file extension:')
f=file_name.split('.')
print(f[-1])

xlsx


In [169]:
# # python program to write arrange the string in order format.
dic = {1:"Hello prasad",2:"hi",3:"Wel come to Cisco network"} 
def arrange(dic):
    for i in dic.keys():
        for j in dic.keys():
            if len(dic[i])<=len(dic[j]):
                dic[i],dic[j]=dic[j],dic[i]
    return dic
arrange(dic)

{1: 'hi', 2: 'Hello prasad', 3: 'Wel come to Cisco network'}

In [175]:
# # print all letters except c an t

string = "copyassignment"

for i in string:
    if i=="c" or i=="t":
        continue
    else:
        print(i)


o
p
y
a
s
s
i
g
n
m
e
n


In [176]:
 # find the number which consists of 1
lst=[11,12,34,111,112]
for i in lst:
    if str(i).startswith('1'):
        print(i)

11
12
111
112


In [1]:
# # Python program to find the unique elements and count.

a="abcdabcdbb"

s = ""
count=1
for i in a:
    if i not in s:
        s+=i
        count+=1
print(s,count)

abcd 5


In [4]:
# add the value t dict
dictt = {'one':1,'two':2,'three':3}
for i in dictt.keys():
    dictt[i]=dictt[i]+1
print(dictt)

{'one': 2, 'two': 3, 'three': 4}


In [25]:
# # find the highest number
def highest_num(a,b,c):
    if a>b and a>c:
        print('a is highest')
    elif b>c:
        print('b is highest')
    else:
        print('c is highest')
highest_num(1,2,3)

c is highest


In [26]:
# # split the list
string = 'ojas innovative technologies'.split()
print(string)
print(' '.join(string))

['ojas', 'innovative', 'technologies']
ojas innovative technologies


In [30]:
# # Default string arguments 
string = "{} {} and {}".format('ojas','innovative','tech')
print(string)

# # positional string arguments 
string = "{0} {1} and {2}".format('ojas','innovative','tech')
print(string)

# # keyword arguments
string = "{a} {b} and {c}".format(a='ojas',b='innovative',c='tech')
print(string)

ojas innovative and tech
ojas innovative and tech
ojas innovative and tech


In [1]:
# Polyndrme
num = 121
temp =num
rev = 0 
while temp>0:
    dig = temp%10
    rev = rev*10+dig
    temp = temp//10
if num==rev:
    print('palyndrme')
else:
    print("Nt paly")
    

polyndrme


In [12]:
# Gather the all names in one list and all integers in one list.
array = [{'name':'tejesh','age':28},{'name':'bhargav','age':27},{'name':'pavan','age':29}]
result ={}
for item in array:
    for key,value in item.items():
        if key in result:
            result[key].append(value)
        else:
            result[key] = [value]
print(result)


{'name': ['tejesh', 'bhargav', 'pavan'], 'age': [28, 27, 29]}


In [11]:
array = [{'name':'tejesh','age':28},{'name':'bhargav','age':27},{'name':'pavan','age':29}]
result = {}
for item in array:
    for key,value in item.items():
        if key in result:
            result[key].append(value)
        else:
            result[key]=[value]
print(result)

{'name': ['tejesh', 'bhargav', 'pavan'], 'age': [28, 27, 29]}


In [13]:
# Given a list of integers, write a Python function to find the maximum product of any three numbers from the list.

# Example: Input: [1, 2, 3, 4, 5], Output: 60 (4 * 5 * 3)

lst = [1,2,3,4]
lst.sort()
print(lst[-1]*lst[-2]*lst[-3])

24


In [15]:
# Given a matrix represented as a 2D list of integers, write a Python function to rotate the matrix by 90 degrees clockwise.

# Example: Input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]], Output: [[7, 4, 1], [8, 5, 2], [9, 6, 3]]

array =[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

length = len(array)

for i in range(length):
    for j in range(i+1,length):
        array[i][j],array[j][i]=array[j][i],array[i][j]
for i in range(length):
    array[i]=array[i][::-1]
print(array)






[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [16]:
# Given two sorted lists of integers, write a Python function to merge them into a single sorted list.
# Example: Input: [1, 3, 5], [2, 4, 6], Output: [1, 2, 3, 4, 5, 6]

li1 = [1,3,5]
li2 = [2,4,6]
print(li1+li2)

[1, 3, 5, 2, 4, 6]


In [27]:

# Given a list of integers li and a target value, write a Python function to find all unique pairs of numbers in the list that add up to the target. Implement the function find_number_pairs(li, target) that takes the list li and the target value as input and returns a list of tuples representing the pairs.
li = [4, 3, 1, 6, 8, 5, 2]
target = 7
result =[]
def unique_pairs(li):
    for i in range(len(li)):
        for j in range(i+1,len(li)):
            if li[i]+li[j]==target:
                result.append((i,j)) # output as index position [(0, 1), (2, 3), (5, 6)]

    return result
print(unique_pairs(li))

li = [4, 3, 1, 6, 8, 5, 2]
target = 7
result =[]
def unique_pairs(li):
    for i in range(len(li)):
        for j in range(i+1,len(li)):
            if li[i]+li[j]==target:
                result.append((li[i],li[j])) # output as pairs [(4, 3), (1, 6), (5, 2)]


    return result
print(unique_pairs(li))

[(0, 1), (2, 3), (5, 6)]
[(4, 3), (1, 6), (5, 2)]


In [18]:
# Given a string, write a Python function to find all possible permutations of the characters.
# Given a string, write a Python function to find all possible permutations of the characters.
import itertools
def find_permutations(input_string):
    permutations = list(itertools.permutations(input_string))
    permutations = [''.join(perm) for perm in permutations]
    return permutations

input_string = "abc"
output = find_permutations(input_string)
print(output)

['abc', 'acb', 'bac', 'bca', 'cab', 'cba']


In [20]:
import itertools
string = "abc"
permutation = list(itertools.permutations(string))
permutation = [''.join(i) for i in permutation]
print(permutation)

['abc', 'acb', 'bac', 'bca', 'cab', 'cba']


In [21]:
# Polymorphism
class car:
    def __init__(self,name,cost):
        self.name = name
        self.cost = cost
    def move(self):
        print('drive')
class flight:
    def __init__(self,name,cost):
        self.name = name
        self.cost = cost
    def move(self):
        print('drive')

obj = car('suzuki',100)
obj1 = flight('asisa',300)

for i in (obj,obj1):
    i.move()

drive
drive


In [22]:
from abc import ABC,abstractmethod

class animal(ABC):
    @abstractmethod
    def display(self):
        pass



# Loading data into Pandas

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('pokemon_data.csv')
# print(df.head(5))
# df_xlsx = pd.read_excel('pokemon_data.xlsx')
# print(df_xlsx.head(5))
# df_text = pd.read_csv('pokemon_data.txt',delimiter="\t")
# print(df_text)
# What is this delimiter?
# A delimiter is one or more characters that separate text strings.
# df['HP']
df

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [7]:
# Gather columns into rows
pd.melt(df)

variable value
0             #     1
1             #     2
2             #     3
3             #     3
4             #     4
...         ...   ...
9595  Legendary  True
9596  Legendary  True
9597  Legendary  True
9598  Legendary  True
9599  Legendary  True

[9600 rows x 2 columns]

In [16]:
df.sort_values('Attack',ascending=False)

#                     Name   Type 1    Type 2   HP  Attack  Defense  \
163  150      MewtwoMega Mewtwo X  Psychic  Fighting  106     190      100   
232  214  HeracrossMega Heracross      Bug  Fighting   80     185      115   
424  383    GroudonPrimal Groudon   Ground      Fire  100     180      160   
426  384    RayquazaMega Rayquaza   Dragon    Flying  105     180      100   
429  386       DeoxysAttack Forme  Psychic       NaN   50     180       20   
..   ...                      ...      ...       ...  ...     ...      ...   
139  129                 Magikarp    Water       NaN   20      10       55   
261  242                  Blissey   Normal       NaN  255      10       10   
230  213                  Shuckle      Bug      Rock   20      10      230   
121  113                  Chansey   Normal       NaN  250       5        5   
488  440                  Happiny   Normal       NaN  100       5        5   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
163      154      100    130           1       True  
232       40      105     75           2      False  
424      150       90     90           3       True  
426      180      100    115           3       True  
429      180       20    150           3       True  
..       ...      ...    ...         ...        ...  
139       15       20     80           1      False  
261       75      135     55           2      False  
230       10      230      5           2      False  
121       35      105     50           1      False  
488       15       65     30           4      False  

[800 rows x 12 columns]

In [21]:
df.rename(columns={'Attack':'attack'})

#                   Name   Type 1  Type 2  HP  attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [25]:
df.sort_index()

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [ ]:
df.drop()

In [28]:
df.reset_index()

index    #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0        0    1              Bulbasaur    Grass  Poison  45      49       49   
1        1    2                Ivysaur    Grass  Poison  60      62       63   
2        2    3               Venusaur    Grass  Poison  80      82       83   
3        3    3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4        4    4             Charmander     Fire     NaN  39      52       43   
..     ...  ...                    ...      ...     ...  ..     ...      ...   
795    795  719                Diancie     Rock   Fairy  50     100      150   
796    796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797    797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798    798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799    799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

# Reading Data in Pandas

In [7]:
# Reading Headers
df.columns
# Read each column
# df[['Name','HP','Generation']]
df[['Name','HP','Generation']]
# Read each row
# print(df1.iloc[0:4])
for index,row in df.iterrows():
    print(index,row['Name'])


0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 

In [8]:
# fetch if column equal to poison 
df.loc[df['Type 2']=='Poison']

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65   
1      2                Ivysaur  Grass  Poison   60      62       63       80   
2      3               Venusaur  Grass  Poison   80      82       83      100   
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
16    13                 Weedle    Bug  Poison   40      35       30       20   
17    14                 Kakuna    Bug  Poison   45      25       50       25   
18    15               Beedrill    Bug  Poison   65      90       40       45   
19    15  BeedrillMega Beedrill    Bug  Poison   65     150       40       15   
48    43                 Oddish  Grass  Poison   45      50       55       75   
49    44                  Gloom  Grass  Poison   60      65       70       85   
50    45              Vileplume  Grass  Poison   75      80       85      110   
53    48                Venonat    Bug  Poison   60      55       50       40   
54    49               Venomoth    Bug  Poison   70      65       60       90   
75    69             Bellsprout  Grass  Poison   50      75       35       70   
76    70             Weepinbell  Grass  Poison   65      90       50       85   
77    71             Victreebel  Grass  Poison   80     105       65      100   
78    72              Tentacool  Water  Poison   40      40       35       50   
79    73             Tentacruel  Water  Poison   80      70       65       80   
99    92                 Gastly  Ghost  Poison   30      35       30      100   
100   93                Haunter  Ghost  Poison   45      50       45      115   
101   94                 Gengar  Ghost  Poison   60      65       60      130   
102   94      GengarMega Gengar  Ghost  Poison   60      65       80      170   
181  167               Spinarak    Bug  Poison   40      60       40       40   
182  168                Ariados    Bug  Poison   70      90       70       60   
227  211               Qwilfish  Water  Poison   65      95       75       55   
292  269                 Dustox    Bug  Poison   60      50       70       50   
344  315                Roselia  Grass  Poison   50      60       45      100   
451  406                  Budew  Grass  Poison   40      30       35       50   
452  407               Roserade  Grass  Poison   60      70       65      125   
603  543               Venipede    Bug  Poison   30      45       59       30   
604  544             Whirlipede    Bug  Poison   40      55       99       40   
605  545              Scolipede    Bug  Poison   60     100       89       55   
651  590                Foongus  Grass  Poison   69      55       45       55   
652  591              Amoonguss  Grass  Poison  114      85       70       85   

     Sp. Def  Speed  Generation  Legendary  
0         65     45           1      False  
1         80     60           1      False  
2        100     80           1      False  
3        120     80           1      False  
16        20     50           1      False  
17        25     35           1      False  
18        80     75           1      False  
19        80    145           1      False  
48        65     30           1      False  
49        75     40           1      False  
50        90     50           1      False  
53        55     45           1      False  
54        75     90           1      False  
75        30     40           1      False  
76        45     55           1      False  
77        70     70           1      False  
78       100     70           1      False  
79       120    100           1      False  
99        35     80           1      False  
100       55     95           1      False  
101       75    110           1      False  
102       95    130           1      False  
181       40     30           2      False  
182       60     40           2      False  
227       55     85           2      False  
2

In [9]:
#Read specific locationdf
df.iloc[227,1]

'Qwilfish'

# Sorting/Describing Data

In [10]:
df.sort_values(['Name','Type 1'],ascending=[1,0])
df

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

#  Making Changes to the data

In [11]:
df['Total'] = df['HP']+df['Attack']
df = df.drop(columns=['Total'])
df['Total'] = df.iloc[:,4:10].sum(axis=1)
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]]+ cols[4:12]]
df.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

# saving our data (Exporting into Desired Format)


In [12]:
df.to_csv('modified.csv',index=False)
df.to_csv('modified.xlsx',index=False)
df.to_csv('modified.txt',index=False,sep="\t")

# Filtering Data

In [13]:
new_df = df.loc[(df['Type 1']=='Grass') & (df['Type 2']=="Poison") & (df['HP']>70)]
new_df.reset_index(drop=True,inplace=True)
new_df

#                   Name Type 1  Type 2  Total   HP  Attack  Defense  \
0    3               Venusaur  Grass  Poison    525   80      82       83   
1    3  VenusaurMega Venusaur  Grass  Poison    625   80     100      123   
2   45              Vileplume  Grass  Poison    490   75      80       85   
3   71             Victreebel  Grass  Poison    490   80     105       65   
4  591              Amoonguss  Grass  Poison    464  114      85       70   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0      100      100     80           1      False  
1      122      120     80           1      False  
2      110       90     50           1      False  
3      100       70     70           1      False  
4       85       80     30           5      False

# Conditional Changes

In [14]:
df.loc[df['Total'] > 500, ['Generation','Legendary']] = ['Test 1', 'Test 2']
df
df = pd.read_csv('modified.csv')
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

# Aggregate Statistics

In [15]:
df = pd.read_csv('modified.csv')
df['count'] = 1
df.groupby(['Type 1','Type 2']).count()['count']


Type 1  Type 2  
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

# Working with large amunts of data


In [16]:
new_df = pd.DataFrame(columns=df.columns)

for df in pd.read_csv('modified.csv', chunksize=5):
    results = df.groupby(['Type 1']).count()
    
    new_df = pd.concat([new_df, results])
new_df

# Name Type 1 Type 2 Total HP Attack Defense Sp. Atk Sp. Def Speed  \
Fire     1    1    NaN      0     1  1      1       1       1       1     1   
Grass    4    4    NaN      4     4  4      4       4       4       4     4   
Fire     4    4    NaN      3     4  4      4       4       4       4     4   
Water    1    1    NaN      0     1  1      1       1       1       1     1   
Bug      2    2    NaN      0     2  2      2       2       2       2     2   
...     ..  ...    ...    ...   ... ..    ...     ...     ...     ...   ...   
Fairy    1    1    NaN      0     1  1      1       1       1       1     1   
Flying   2    2    NaN      2     2  2      2       2       2       2     2   
Fire     1    1    NaN      1     1  1      1       1       1       1     1   
Psychic  2    2    NaN      2     2  2      2       2       2       2     2   
Rock     2    2    NaN      2     2  2      2       2       2       2     2   

        Generation Legendary count  
Fire             1         1   NaN  
Grass            4         4   NaN  
Fire             4         4   NaN  
Water            1         1   NaN  
Bug              2         2   NaN  
...            ...       ...   ...  
Fairy            1         1   NaN  
Flying           2         2   NaN  
Fire             1         1   NaN  
Psychic          2         2   NaN  
Rock             2         2   NaN  

[433 rows x 14 columns]

In [17]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even_numbers = list(map(lambda x : x if x%2==0 else 'odd',numbers))
even_numbers


['odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd', 10]

In [18]:
names1 = ['Amir', 'Bala', 'Chales']
 
if 'amir' in names1:
    print(1)
else:
    print(2)

2


In [19]:
names1 = ['Amir', 'Bala', 'Charlie']
names2 = [name.lower() for name in names1]
 
print(names2[2][0])

c


In [20]:
numbers = [1, 2, 3, 4]
 
numbers.append([2,3])
print(numbers)
print(len(numbers))

[1, 2, 3, 4, [2, 3]]
5


In [21]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
 
print(len(list1 + list2))

8


In [22]:
def addItem(listParam):
    listParam += [1]
 
mylist = [1, 2, 3, 4]
addItem(mylist)
print(len(mylist))

5


In [23]:
veggies = ['carrot', 'broccoli', 'potato', 'asparagus']
veggies.insert(veggies.index('broccoli'), 'celery')
print(veggies)

['carrot', 'celery', 'broccoli', 'potato', 'asparagus']


In [11]:
lst1 = [1,2,3]
lst2 = [3,4,5]

result = map(lambda x,y:x+y,lst1,lst2)
print(list(result))

result = [x +y for x,y in zip(lst1,lst2)]
print(result)

[4, 6, 8]
[4, 6, 8]


# Numpy

In [14]:
import numpy as np

In [15]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0][1])

2


# How to create a basic Array

In [19]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
np.zeros(2)

array([0., 0.])

In [24]:
np.ones(1)

array([1.])

In [28]:
# create an empty array with 2 elements
np.empty(4)

array([2.12199579e-314, 9.99460018e-312, 7.82599983e-321, 6.95250784e-310])

In [31]:
np.arange(1,10,3)

array([1, 4, 7])

In [44]:
np.linspace(0,360,endpoint=True)

array([  0.        ,   7.34693878,  14.69387755,  22.04081633,
        29.3877551 ,  36.73469388,  44.08163265,  51.42857143,
        58.7755102 ,  66.12244898,  73.46938776,  80.81632653,
        88.16326531,  95.51020408, 102.85714286, 110.20408163,
       117.55102041, 124.89795918, 132.24489796, 139.59183673,
       146.93877551, 154.28571429, 161.63265306, 168.97959184,
       176.32653061, 183.67346939, 191.02040816, 198.36734694,
       205.71428571, 213.06122449, 220.40816327, 227.75510204,
       235.10204082, 242.44897959, 249.79591837, 257.14285714,
       264.48979592, 271.83673469, 279.18367347, 286.53061224,
       293.87755102, 301.2244898 , 308.57142857, 315.91836735,
       323.26530612, 330.6122449 , 337.95918367, 345.30612245,
       352.65306122, 360.        ])

In [45]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
# How do you know the shape and size of an array?


In [50]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [51]:
array_example.ndim

3

In [52]:
array_example.size

24

In [53]:
array_example.shape

(3, 2, 4)

In [54]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [55]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [56]:
np.reshape(a,newshape=(1,6),order='C')


array([[0, 1, 2, 3, 4, 5]])

In [57]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [58]:
print(a[a<5])

[1 2 3 4]


In [60]:
divisible = a[a%2==0]
divisible

array([ 2,  4,  6,  8, 10, 12])

In [1]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

NameError: name 'np' is not defined

In [3]:
# Write a Python program to sum all the items in a list.
lst = [1,2,3,4,5]
sum = 0
for i in lst:
    sum+=i
print(sum)

result = [i+i for i in lst ]
print(result)

15
[2, 4, 6, 8, 10]


In [8]:
# Write a Python program to multiply all the items in a list.
lst = [1,2,3,4]
mul = 1

for i in lst:
    mul*=i
print(mul)




24


In [12]:
#  Write a Python program to count the number of strings from a given list of strings. The string length is 2 or more and the first and last characters are the same.
lst = ['abc', 'xyz', 'aba', '1221','madam']

count = 0
for i in lst:
    if len(lst) > 1 and i[0] == i[-1]:   
        count+=1
print(count)


3


In [14]:
# Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples.

# Expected Result : [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]

lst = [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]

print(sorted(lst,key= lambda x:x[-1]))



[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [15]:
# 7. Write a Python program to remove duplicates from a list.

lst = [1,2,3,1,2,3,4,5,6,6,5,4]
print(set(lst))

{1, 2, 3, 4, 5, 6}


In [19]:
# Write a Python program to check if a list is empty or not.
lst = [1]
if not lst:
    print("List is empty")

In [22]:
# Write a Python program to find the list of words that are longer than n from a given list of words.
string =  "The quick brown fox jumps over the lazy dog"
n = 3

split_string = string.split()
print(split_string)
for i in split_string:
    if len(i)>n:
        print(i)


['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
quick
brown
jumps
over
lazy


In [25]:
# Write a Python function that takes two lists and returns True if they have at least one common member.
def common_list(lst1,lst2):
    if lst1==lst2:
        return True
    else:
        return False
lst1 = [1,2,3,4]
lst2 = [1,2,3,4]
print(common_list(lst1,lst2))

True


In [27]:
# Write a Python program to print a specified list after removing the 0th, 4th and 5th elements.
lst = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
# output : ['Green', 'White', 'Black']

print(lst[1:4])

['Green', 'White', 'Black']


In [6]:
# Write a Python program to find those numbers which are divisible by 7 and multiples of 5, between 1500 and 2700 (both included).
empty = []
for i in range(1500,2700+1):
    if i%7==0 and i%5==0:
        empty.append(str(i))
print(','.join(empty))

1505,1540,1575,1610,1645,1680,1715,1750,1785,1820,1855,1890,1925,1960,1995,2030,2065,2100,2135,2170,2205,2240,2275,2310,2345,2380,2415,2450,2485,2520,2555,2590,2625,2660,2695


In [11]:
import random
target_num, guess_num = random.randint(1, 10),0
while target_num != guess_num:
    guess_num = int(input('Guess a number between 1 and 10 until you get it right : '))
print('Well guessed!')

True
False
Well guessed!


In [12]:
n=5
for i in range(n):
    for j in range(i):
        print ('* ', end="")
    print('')

for i in range(n,0,-1):
    for j in range(i):
        print('* ', end="")
    print('')


* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [30]:
# Write a Python program that prints each item and its corresponding type from the following list.

datalist = [1452, 11.23, 1+2j, True, 'w3resource', (0, -1), [5, 12], {"class":'V', "section":'A'}]

for i in datalist:
    print('each item',i,"type of element",type(i))


each item 1452 type of element <class 'int'>
each item 11.23 type of element <class 'float'>
each item (1+2j) type of element <class 'complex'>
each item True type of element <class 'bool'>
each item w3resource type of element <class 'str'>
each item (0, -1) type of element <class 'tuple'>
each item [5, 12] type of element <class 'list'>
each item {'class': 'V', 'section': 'A'} type of element <class 'dict'>


In [43]:
# Write a Python program that prints all the numbers from 0 to 6 except 3 and 6.
# Note : Use 'continue' statement.
# Expected Output : 0 1 2 4 5

for i in range(0,8):
    if i==3 or i==6:
        continue
    print(i,end=' ')
# print('\n')

0 1 2 4 5 7 

In [46]:
x,y=0,1

while y<50:
    print(y)
    x,y = y,x+y

1
1
2
3
5
8
13
21
34


In [54]:
x,y = 0,1
while y<10:
    print(y)
    x,y = y,x+y

1
1
2
3
5
8


In [62]:
for fizzbuzz in range(10):
    if fizzbuzz % 3 == 0 and fizzbuzz % 5 == 0:
        print("fizzbuzz")
        continue
    elif fizzbuzz % 3 == 0:
        print("fizz")
        continue
    elif fizzbuzz % 5 == 0:
        print("buzz")
        continue
  

fizzbuzz
fizz
buzz
fizz
fizz


In [69]:
s = input("Input a string")
d=l=0
for c in s:
    if c.isdigit():
        d=d+1
    elif c.isalpha():
        l=l+1
if d==10:
    print('valid phone number',d)
else:
    print('not valid')

valid phone number


In [73]:
d='7095920568'
print(len(d)==10)

True


In [93]:
li = []
for i in range(100,401):
    s = str(i)
    if (int(s[0])%2==0) and (int(s[1])%2==0) and (int(s[2])%2==0):
        li.append(s)
print(",".join(li))

200,202,204,206,208,220,222,224,226,228,240,242,244,246,248,260,262,264,266,268,280,282,284,286,288,400


In [87]:
items = []
for i in range(100, 401):
    s = str(i)
    if (int(s[0])%2==0) and (int(s[1])%2==0) and (int(s[2])%2==0):
        items.append(s)
print( ",".join(items))


200,202,204,206,208,220,222,224,226,228,240,242,244,246,248,260,262,264,266,268,280,282,284,286,288,400


In [96]:

li = [3, 7, 5, 4, 3, 2, 1]
sorted_li = sorted(li, reverse=True, key=lambda x: (x != 3, x))

print(sorted_li)



[7, 5, 4, 2, 1, 3, 3]


In [11]:
def deco(check):
    def Inner(username,password):
        if username=="Bhargav" and password=="Bhargav":
            return "Valid"
        else:
            return check(username,password)
    return Inner     
@deco
def check(username,password):
    return "Invalid"
print(check("Bhargav","Bhargav"))

Valid
